project:
  type: website
  output-dir: docs

website:
  # title: "Basil Okola"
  open-graph: true
  site-url: https://bokola.github.io/
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      # - about.qmd
      - resources.qmd
      - href: CV/CV-Basil-Owiti-Okola.pdf
      - text: cv
      - target: _blank
      - posts.qmd
page-footer:
execute: 
  background: light

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

